# Generated by Django 3.2 on 2022-02-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dependencias',
            constraint=models.UniqueConstraint(fields=('sedesClinica', 'serviciosSedes', 'servicios', 'subServicios', 'numero', 'dependenciasTipo'), name='Constraint_dependencias'),
        ),
    ]
