# Generated by Django 3.2 on 2022-02-06 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0002_initial'),
        ('usuarios', '0001_initial'),
        ('sitios', '0003_dependencias_constraint_dependencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependenciasactual',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='dependenciasactual',
            name='nombre',
        ),
        migrations.AddField(
            model_name='dependenciasactual',
            name='disponibilidad',
            field=models.CharField(choices=[('L', 'LIBRE'), ('O', 'OCUPADA')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='dependenciasactual',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='dependenciasactual',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AlterField(
            model_name='dependenciasactual',
            name='documento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoDepAct', to='usuarios.usuarios'),
        ),
    ]
