# Generated by Django 3.2 on 2022-02-06 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('planta', '0002_initial'),
        ('sitios', '0004_auto_20220206_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='historialDependencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consec', models.IntegerField()),
                ('fechaOcupacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fechaLiberacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('dependencias', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.dependencias')),
                ('documento', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentohistorialDep', to='usuarios.usuarios')),
                ('tipoDoc', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento')),
                ('usuarioRegistro', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta')),
            ],
        ),
    ]
