# Generated by Django 3.2 on 2022-02-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitios', '0001_initial'),
        ('clinico', '0001_initial'),
        ('planta', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='id_centro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.centros'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='id_ciudad',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ciudades'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='id_departamento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='id_especialidad',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='id_tipo_doc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='documento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='id_TipoExamen',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='id_examen',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='id_tipo_doc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='documento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='id_TipoExamen',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='id_examen',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='id_tipo_doc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='historia',
            name='documento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='historia',
            name='id_especialidad',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades'),
        ),
        migrations.AddField(
            model_name='historia',
            name='id_medico',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.medicos'),
        ),
        migrations.AddField(
            model_name='historia',
            name='id_tipo_doc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='examenes',
            name='id_TipoExamen',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='id_especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='id_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
    ]
